### ISSUE TITLE
המשחק התחיל ישר בלי הסבר + נתקע המשחק

### ISSUE THREAD

**Issue by Michael-Aga** [ParkPulse-dev/ParkPulse#10]
המשחק ישר התחיל למרוץ בלי להסביר מה הולך ואיך משחקים בנוסף כשניצחתי זה הגיע למסך טעינה ונתקע שם ולא זז
![image](https://github.com/ParkPulse-dev/ParkPulse/assets/85742675/43889f38-a3b3-4597-ae1c-0248ae0dbb1f)

בנוסף המסך ענק צריך להקטין קצת

**Comment by Dorshir** [comment]
Thanks, Fixed multiplayer settings, so it will load the loby. Tutorial is also fixed.
