### ISSUE TITLE
אחרי שנגמר הזמן

### ISSUE THREAD

**Issue by HadarBitan** [ParkPulse-dev/ParkPulse#11]
אחרי שנגמר הזמן מופיע המילה DRAW  על המסך ואז לא מבינים מה לעשות אז לוחצים על החץ ופשוט זה נתקע במסך כלשהו ואין מושג איך להמשיך משם.

![image](https://github.com/ParkPulse-dev/ParkPulse/assets/86705118/269262e8-b62e-4042-8399-b396a6de7a96)

**Comment by Dorshir** [comment]
Thanks, fixed.
