### ISSUE TITLE
מסך פתיחה ותאונה

### ISSUE THREAD

**Issue by MatanAdar** [ParkPulse-dev/ParkPulse#15]
המשחק נראה טוב אבל חסר מסך פתיחה שממנו אפשר לעבור לתדרוך או משחק ישר ובנוסף כאשר מתנגשים ברכב אין שום עונש ככה שאפשר להמשיך להתנגש. לפי דעתי צריך להוסיף עונש או שמתחילים את השלב מחדש שמתנגשים.

**Comment by Dorshir** [comment]
Fixed everything. Thank you.
