### ISSUE TITLE
Controls are never explained before the start of the game

### ISSUE THREAD

**Issue by yonatan-ratner** [ParkPulse-dev/ParkPulse#3]
this, in addition with the time pressure to finish the game, leads to a feeling of frustration.

**Comment by yonatan-ratner** [comment]
This differs from issue #2, as he describes a control 'switch' mechanic which is also not explained.

**Comment by Dorshir** [comment]
Thanks, fixed the tutorial with explanations.

**Comment by Dorshir** [comment]
Thanks, fixed the tutorial with explanations.
