### ISSUE TITLE
 גודל המסך+ הסבר +המסלול לא נכון צריך קודם לאסוף סמלים ואז ללכת אחרי החצים 

### ISSUE THREAD

**Issue by ohadtaizi** [ParkPulse-dev/ParkPulse#5]
לא כתוב מה צריך לעשות ,הלכתי לפי החצים החנתי את הרכב ולא קרה כלום . מצד החד הנכשתי ברכבים ולא קרה לי כלום מצד שני התנגשתי בעץ הרכב התפוצץ לא כתוב לי הפסדת או כפתור שמחזיר אותי לנקודת ההתחלה או התחל מדחש .
אחרי שהמשכתי לשחק אספתי את 3 הסמלים המשכתי לחניה וסיימתי את המשחק .
יש לשנות את גודל המסך כך שנראה את כל המסך

**Comment by Dorshir** [comment]
Thanks, fixed the tutorial with explanations. also collision leads to an explosion, and tp you back to the beggining. ratio is also fixed.
