### ISSUE TITLE
When car is crashed the time continues to count + controlls never explained

### ISSUE THREAD

**Issue by ofekrotem** [ParkPulse-dev/ParkPulse#9]
When I crashed the car into a tree the game is still continuing to count back time. No option to see score/play again/stop the game

![image](https://github.com/ParkPulse-dev/ParkPulse/assets/92383710/4a5aabe8-a71f-4cbf-ab29-7e5e36f2cfc1)

**Comment by Dorshir** [comment]
Thanks, Fixed tutorial, score in multiplayer, time, reset player when crash.
